---
- name: set up web server
  ignore_errors: yes
  hosts: lcsa-centos
  tasks:
    - name: install httpd
      yum: name=httpd
  tasks:
    - name: copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted
...
