---
- name: install httpd
  hosts: lcsa-ubuntu
  tasks:
    - name: install package
      package:
        name: httpd
        state: present
    - name: create an index.html
      copy:
        content: 'welcom to this web server'
        dest: /var/www/html/index.html
    - name: start the service
      service:
        name: httpd
        state: started
        enabled: true
    - name: open firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
...
