---
- name: create sudo user
  hosts: all
  vars:
    my_user: linda
    superusers:
     - root
     - linda
  tasks:
    - name: run only if linda is superuser
      user:
        name: "{{ my_user }}"
        groups: wheel
        append: yes
      when: my_user in superusers

...

