apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd2
  namespace: default
spec:
  ports:
  - nodePort: 31773
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: httpd
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: v1
kind: Pod
metadata:
  name: httpd2
  namespace: default
  labels:
    app: httpd
spec:
  containers:
  - name: busy
    image: centos:7
    ports:
      - containerPort: 80
    command:
      - sleep 
      - "3600"

# exec into the pod
# install httpd
# enable the service by simple running /usr/sbin/httpd
# alternative way of creating the service
# kubectl expose pod httpd2 --type=LoadBalancer
