apiVersion: v1
kind: Pod
metadata:
  name: ready-togo
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - containerPort: 80
  - name: app
    image: busybox
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
    command: ['sleep', '3600']
