apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretservice
  labels:
    app: secret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers:
      - name: my-secret-container
        image: alpine
        volumeMounts:
        - name: secret
          mountPath: /etc/users
        command: ["sleep", "3000"]
      volumes:
      - name: secret
        secret:
          secretName: mysecret
  
