apiVersion: v1
kind: Service
metadata:
  name: nginxss
  labels:
    app: nginxss
spec:
  ports:
  - port: 80
    name: web
  ClusterIP: none
  seletor:
    app: nginxss

---
apiVersion: v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginxss
  serviceName: "nginxss"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxss
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginxss
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: ["ReadWriteOnce" ]
      storageClassName: "my-storage-class" ]
      resources:
        requests:
          storage: 1Gi

