global:
  scrape_interval: 5s
  external_labels:
    monitor: 'Monitoring'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.17.0.4:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.17.0.4:9100']
  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['172.17.0.4:8080']
