apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chartmuseum
    app.kubernetes.io/managed-by: Helm
    chart: chartmuseum-2.15.0
    heritage: Helm
    release: local-chartmuseum
  name: local-chartmuseum-chartmuseum
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: chartmuseum
      release: local-chartmuseum
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: chartmuseum
        release: local-chartmuseum
      name: local-chartmuseum-chartmuseum
    spec:
      containers:
      - args:
        - --port=8080
        - --storage-local-rootdir=/storage
        env:
        - name: CHART_POST_FORM_FIELD_NAME
          value: chart
        - name: DISABLE_API
          value: "true"
        - name: DISABLE_METRICS
          value: "true"
        - name: LOG_JSON
          value: "true"
        - name: PROV_POST_FORM_FIELD_NAME
          value: prov
        - name: STORAGE
          value: local
        image: chartmuseum/chartmuseum:v0.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: chartmuseum
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /storage
          name: storage-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: storage-volume
