---
- name: remove httpd
  hosts: lcsa-ubuntu
  tasks:
    - name: close firewall
      firewalld:
        service: http
        permanent: yes
        state: disabled
    - name: remove file
      file:
        path: /var/www/html/index.html
        state: absent
    - name: remove package
      package:
        name: httpd
        state: absent
...
