---
- name: using multiple conditions
  gather_facts: yes
  hosts: all
  tasks:
  - package:
      name: httpd
      state: removed
    when: >
      ( ansible_distribution == "Ubuntu" and
        ansible_memfree_mb > 512 )
      or
      ( ansibile_distribution == "CentOS" and
        ansible_memfree_mb < 1024 )

...
